name: bastet
base: core18
version: '0.43.2'
license: 'GPL-3.0'
summary: 'Bastet is a ncurses Tetris clone with a bastard algorithm.'
description: |
  Bastet stands for "bastard tetris", and is a simple ncurses-based Tetris(R) clone 
  for Linux. Unlike normal Tetris(R), however, Bastet does not choose your next 
  brick at random. Instead, Bastet uses a special algorithm designed to choose the worst
  brick possible. As you can imagine, playing Bastet can be a very frustrating experience!
grade: stable
confinement: strict

apps:
  bastet:
    command: bastet
    environment:
      HOME: $SNAP_USER_COMMON

parts:
  bastet:
    plugin: make
    source: https://github.com/fph/bastet
    source-type: git
    override-build: |
      make
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/usr/bin/
      cp bastet ${SNAPCRAFT_PART_INSTALL}/usr/bin/
    build-packages:
      - liberror-perl
      - build-essential
      - libboost-all-dev
      - libboost1.65-all-dev
      - libncurses5-dev
    stage-packages:
      - libpsm-infinipath1
      - libboost-program-options1.65.1
